/**
 * Cross-cutting knowledge shared by every persona so each bot understands the
 * whole platform — what CleanCookIQ is, the clean-cooking journey (pipeline
 * stages), and the fuels/technologies — not just its own corner. Composed into
 * each persona's knowledge in ../index.ts.
 *
 * Data-privacy answers differ per role (different support link + who-sees-what
 * wording), so those are generated by `dataPrivacyEntry()` rather than shared
 * verbatim.
 */

import type { KnowledgeEntry } from "../types";

export const sharedKnowledge: KnowledgeEntry[] = [
  {
    id: "what-is-cleancookiq",
    topic: "What CleanCookIQ is",
    keywords: [
      "what is cleancookiq", "what is this", "what is the platform", "about cleancookiq",
      "what does the platform do", "overview", "cleancookiq", "ccq", "purpose", "mission",
    ],
    answer:
      "**CleanCookIQ** is Kenya's clean-cooking transition platform. It brings institutions (schools, hospitals, prisons, hotels), suppliers, funders, CSR partners, utilities and researchers onto one shared record so an institution can move from smoky firewood/charcoal to clean cooking — LPG, electric, biogas, briquettes or steam — with the assessment, financing, delivery and monitoring all tracked in one place.",
    followups: ["What's the clean-cooking journey?", "What cooking options are there?", "How is my data protected?"],
  },
  {
    id: "journey-pipeline",
    topic: "The clean-cooking journey",
    keywords: [
      "journey", "pipeline", "stages", "stage", "process", "steps", "lifecycle", "how it works",
      "roadmap", "transition", "from start to finish", "what happens next",
    ],
    answer:
      "Every institution moves through the same transparent pipeline:\n\n1. **Listed** — added to the platform.\n2. **Contacted** — first outreach made.\n3. **Assessed** — kitchen, fuel use and meals surveyed.\n4. **Scored** — rated on the readiness rubric.\n5. **Solution Selected** — the least-cost clean-cooking path chosen.\n6. **Provider Assigned** — a verified supplier is matched.\n7. **Funded** — financing secured.\n8. **Being Installed** — equipment delivered and commissioned.\n9. **Being Monitored** — ongoing DMRV (digital monitoring, reporting & verification) of fuel saved and carbon cut.",
    followups: ["What is the readiness score?", "What cooking options are there?"],
  },
  {
    id: "fuels-equipment",
    topic: "Cooking fuels & equipment",
    keywords: [
      "fuel", "fuels", "cooking method", "technology", "technologies", "equipment", "options",
      "lpg", "electric", "induction", "biogas", "briquette", "briquettes", "steam", "firewood",
      "charcoal", "ethanol", "pellets", "cookstove", "stove",
    ],
    answer:
      "Institutions usually start on **firewood** or **charcoal** (smoky, costly, high-emission). CleanCookIQ profiles cleaner options and the least-cost path for each kitchen:\n\n- **LPG** — clean gas burners; fast, controllable, widely available.\n- **Electric (induction)** — highest efficiency, zero on-site emissions; best where power is reliable.\n- **Biogas** — on-site digester turning waste into cooking gas.\n- **Briquettes** — compressed biomass in efficient stoves; renewable and low-cost.\n- **Steam** — a central boiler feeding steam-jacketed pots for the very largest kitchens.",
    followups: ["What's the clean-cooking journey?", "What is the readiness score?"],
  },
];

/**
 * Build a role-specific "how is my data protected" answer. Every role gets a
 * reassuring, accurate explanation of the platform's role-based access model,
 * pointing at its own support/contact route.
 */
export function dataPrivacyEntry(supportPath: string, roleLine: string): KnowledgeEntry {
  const isTicket = supportPath.includes("support");
  const link = isTicket ? `[open a ticket](${supportPath})` : `[book a demo](${supportPath})`;
  return {
    id: "data-privacy",
    topic: "Your data & privacy",
    keywords: [
      "privacy", "data protection", "confidential", "confidentiality", "gdpr", "my data",
      "who can see", "who sees", "who can access", "is my data safe", "data safe", "secure",
      "shared with", "visible to", "protect my data", "data policy", "other users see",
      "can others see", "personal data", "pii",
    ],
    answer:
      `Your data is private and **role-based**. ${roleLine} Everyone only sees what's relevant to their role, and information is shared between parties only when it's needed for a matched project. You can't see other organisations' private details, and they can't see yours. Questions about who can access your data? ${link}.`,
    followups: ["What is CleanCookIQ?", "How do I get help?"],
  };
}
