/*
 * One-off generator: reads the normalised Makueni survey JSON produced by
 * scripts/extract_makueni_survey.py and emits a Supabase seed migration that
 *   (1) creates the "Makueni County Cooking Baseline" programme if absent, and
 *   (2) inserts the surveyed institutions assigned to it (idempotent — only
 *       seeds when the programme is newly created).
 *
 * Run:  node scripts/gen_makueni_seed.cjs
 * Input:  scripts/data/makueni_institutions.json
 * Output: supabase/migrations/20260904120000_seed_makueni_institutions.sql
 *
 * Not part of the app build. Kept in-repo so the import is reproducible.
 */
const fs = require("fs");
const path = require("path");

const IN = path.join(__dirname, "data", "makueni_institutions.json");
const OUT = path.join(
  __dirname,
  "..",
  "supabase/migrations/20260904120000_seed_makueni_institutions.sql",
);

const PROG_NAME = "Makueni County Cooking Baseline";
const records = JSON.parse(fs.readFileSync(IN, "utf8"));

// ---- helpers -------------------------------------------------------------
const sqlStr = (v) => (v === null || v === undefined || v === "" ? "NULL" : `'${String(v).replace(/'/g, "''")}'`);
// Only emit a bare literal for genuine finite numbers; anything else → NULL, so a
// malformed JSON value can never reach the SQL unquoted.
const sqlNum = (v) => (typeof v === "number" && Number.isFinite(v) ? String(v) : "NULL");

// fuel_type enum has no "none" — no-cooking / unknown rows get a NULL current_fuel.
const FUEL_ENUM = new Set(["firewood", "charcoal", "lpg", "biogas", "electric", "other"]);
const currentFuel = (f) => (f && FUEL_ENUM.has(f) ? f : null);

// meals/day is not surveyed as a count; derive a defensible estimate from the
// population and boarding type (day schools ≈ lunch only; boarding ≈ 3 meals;
// day & boarding ≈ 2). Editable once real figures are known.
const MEALS_FACTOR = { "Day": 1, "Boarding": 3, "Day & Boarding": 2 };
const mealsPerDay = (r) => {
  if (r.population == null) return null;
  return r.population * (MEALS_FACTOR[r.boardingType] ?? 1);
};

// notes preserve everything not mapped to a first-class column: ward, level,
// and the surveyed firewood quantity & monthly cost.
function notesFor(r) {
  const bits = [];
  if (r.ward) bits.push(`Ward: ${r.ward}`);
  if (r.level) bits.push(`Level: ${r.level}`);
  if (r.firewoodKgPerMonth != null) bits.push(`Firewood: ${Math.round(r.firewoodKgPerMonth).toLocaleString()} kg/month`);
  if (r.costKshPerMonth != null) bits.push(`Firewood cost: KES ${Math.round(r.costKshPerMonth).toLocaleString()}/month`);
  return bits.length ? bits.join(" · ") : null;
}

const COLS = [
  "name", "institution_type", "county", "sub_county", "latitude", "longitude",
  "current_fuel", "meals_per_day", "meals_served_per_day", "number_of_students",
  "school_type", "sub_type", "notes", "pipeline_stage",
];

const buildTuples = (pidExpr) => records.map((r) => {
  const meals = mealsPerDay(r);
  const vals = [
    pidExpr,
    sqlStr(r.name),
    sqlStr("school"),          // institution_type — all Makueni rows are schools/TVETs
    sqlStr("Makueni"),
    sqlStr(r.subCounty),
    "NULL",                    // latitude  — no GPS in survey (Phase F geocoding)
    "NULL",                    // longitude
    sqlStr(currentFuel(r.fuel)),
    sqlNum(meals),
    sqlNum(meals),             // meals_served_per_day mirrors the estimate
    sqlNum(r.population),
    sqlStr(r.level),           // school_type = education level
    sqlStr(r.boardingType),    // sub_type = boarding type (drives dataset-card drill-down)
    sqlStr(notesFor(r)),
    "'identified'",
  ];
  return "      (" + vals.join(", ") + ")";
});

const valuesRows = buildTuples("prog_id");
const byBoarding = records.reduce((m, r) => ((m[r.boardingType] = (m[r.boardingType] || 0) + 1), m), {});

const header = `-- ============================================================
-- Seed: Makueni County Cooking Baseline institutions
--
-- Imported from the Makueni County institutional-cooking survey
-- (${records.length} institutions across 6 sub-counties). Source PDF parsed by
-- scripts/extract_makueni_survey.py → scripts/data/makueni_institutions.json,
-- SQL generated by scripts/gen_makueni_seed.cjs.
--
-- Field mapping:
--   institution_type = 'school' (all rows are schools / TVETs)
--   sub_type         = boarding type (Day / Boarding / Day & Boarding)
--   school_type      = education level (Primary/Comprehensive, Secondary, Tertiary/TVET)
--   current_fuel     = surveyed cooking fuel (no-cooking / unknown → NULL)
--   number_of_students = surveyed population
--   meals_per_day / meals_served_per_day = DERIVED estimate (population × 1/2/3
--     by boarding type) — the survey records meal *types*, not counts.
--   notes            = ward · level · firewood kg/month · firewood cost/month
--   latitude/longitude = NULL (survey has no GPS; populated later by geocoding)
--
-- Rows: ${records.length}  (${Object.entries(byBoarding).map(([k, v]) => `${k}: ${v}`).join(", ")})
--
-- Idempotent: institutions are only seeded when the programme row is newly
-- created, so re-running this migration is a no-op.
-- ============================================================
DO $$
DECLARE
  prog_id uuid;
  is_new  boolean := false;
BEGIN
  SELECT id INTO prog_id FROM public.programmes WHERE name = '${PROG_NAME}' LIMIT 1;

  IF prog_id IS NULL THEN
    INSERT INTO public.programmes (name, description, status, county_scope, target_institution_count)
    VALUES (
      '${PROG_NAME}',
      'Baseline pipeline for institutions surveyed in the Makueni County institutional-cooking study — clean-cooking transition tracking across the six sub-counties.',
      'active',
      ARRAY['Makueni'],
      ${records.length}
    )
    RETURNING id INTO prog_id;
    is_new := true;
  END IF;

  IF is_new THEN
    INSERT INTO public.institutions
      (programme_id, ${COLS.join(", ")})
    VALUES
${valuesRows.join(",\n")};
  END IF;
END $$;
`;

fs.writeFileSync(OUT, header);
console.log(`Wrote ${OUT}`);
console.log(`Records: ${records.length}`, byBoarding);
